// GENERATED by scripts/generate-contours.mjs — do not edit by hand.
// The sovereign countries with a recognizable contour in flags/contours/,
// which IS the Flag Party map-round pool. Regenerate after touching the
// generator or worldMap.svg.

/** @type {readonly string[]} */
export const CONTOUR_CODES = ["ae","af","al","am","ao","ar","at","au","az","ba","bd","be","bf","bg","bi","bj","bo","br","bt","bw","by","bz","ca","cd","cf","cg","ch","ci","cl","cm","cn","co","cr","cu","cy","cz","de","dj","dk","do","dz","ec","ee","eg","er","es","et","fi","fr","ga","gb","ge","gh","gm","gn","gq","gr","gt","gw","gy","hn","hr","ht","hu","id","ie","il","in","iq","ir","is","it","jm","jo","jp","ke","kg","kh","kp","kr","kw","kz","la","lb","lk","lr","ls","lt","lv","ly","ma","md","me","mg","mk","ml","mm","mn","mr","mw","mx","my","mz","na","ne","ng","ni","nl","no","np","nz","om","pa","pe","pg","ph","pk","pl","pt","py","qa","ro","rs","rw","sa","sd","se","si","sk","sl","sn","so","sr","ss","sv","sy","sz","td","tg","th","tj","tl","tm","tn","tr","tz","ua","ug","us","uy","uz","ve","vn","ye","za","zm","zw"];

/** @type {ReadonlySet<string>} */
export const CONTOUR_CODE_SET = new Set(CONTOUR_CODES);
