import { scoreRound } from './partyScore.js';

/**
 * Flag Party room — the pure state machine behind the live show. Same shape as
 * `flags/onlineRoom.js` (TTT): every mutation is a reducer that takes a room
 * plus an event and returns `{ room, broadcasts }`, with no DOM and no I/O. The
 * PartyKit server (`party/partyGameServer.js`) is the shell that owns sockets,
 * persistence, and question generation; it resolves round-specific facts
 * (which pool, whether a buzz was correct) and hands the room plain data.
 *
 * The room is deliberately round-agnostic: it never imports a round module.
 * A question is just `{ prompt, options, answer }`; correctness is resolved by
 * the server via the round's `isCorrect` and passed into {@link applyBuzz} as a
 * boolean. That keeps one room engine serving every round type.
 *
 * Phase machine: `lobby` → `question` → `reveal` → (`question` | `final`),
 * and `final` → `lobby` on Play again.
 *
 * @typedef {'lobby' | 'question' | 'reveal' | 'final'} Phase
 * @typedef {{ nickname: string, score: number }} Seat
 * @typedef {{ prompt: string, options: string[], answer: string }} Question
 * @typedef {{ playerId: string, choice: string, correct: boolean }} Buzz
 *
 * @typedef {Object} Room
 * @property {Phase} phase
 * @property {string | null} hostId  playerId of the creator; the only seat that
 *   can start / advance / restart. Sticky across reconnects.
 * @property {Map<string, Seat>} seats  playerId -> seat; insertion order is the
 *   stable display order.
 * @property {Set<string>} present  playerIds with a live socket right now; reset
 *   to empty on every load (a socket can't survive a DO eviction).
 * @property {number} totalRounds
 * @property {number} roundIndex  0-based index of the current question.
 * @property {Question | null} question  the live question; `answer` never leaves
 *   the server until reveal.
 * @property {Buzz[]} buzzes  this question's buzzes in server arrival order.
 *
 * @typedef {{ to: string | 'all', message: object }} Broadcast
 * @typedef {{ room: Room, broadcasts: Broadcast[], rejectConnection?: boolean }} ApplyResult
 */

export const DEFAULT_ROUNDS = 5;

/**
 * @param {number} [totalRounds]
 * @returns {Room}
 */
export function createRoom(totalRounds = DEFAULT_ROUNDS) {
  return {
    phase: 'lobby',
    hostId: null,
    seats: new Map(),
    present: new Set(),
    totalRounds,
    roundIndex: 0,
    question: null,
    buzzes: [],
  };
}

/**
 * A player connects (or reconnects). The first player becomes host. New seats
 * may only join from the lobby — arriving mid-game is rejected so the
 * scoreboard stays fair; a known playerId reconnecting is always welcomed back
 * (sticky seat, sticky host, sticky score).
 *
 * @param {Room} room
 * @param {string} playerId
 * @param {string} nickname
 * @returns {ApplyResult}
 */
export function applyHello(room, playerId, nickname) {
  const isReconnect = room.seats.has(playerId);
  if (!isReconnect && room.phase !== 'lobby') {
    return {
      room,
      broadcasts: [{ to: playerId, message: { type: 'rejected', reason: 'in-progress' } }],
      rejectConnection: true,
    };
  }

  const seats = new Map(room.seats);
  const present = new Set(room.present);
  let hostId = room.hostId;
  const name = cleanName(nickname);

  if (!isReconnect) {
    seats.set(playerId, { nickname: name, score: 0 });
    if (hostId === null) hostId = playerId;
  } else if (name) {
    const existing = /** @type {Seat} */ (seats.get(playerId));
    seats.set(playerId, { ...existing, nickname: name });
  }
  present.add(playerId);

  const nextRoom = { ...room, seats, present, hostId };
  /** @type {Broadcast[]} */
  const broadcasts = [welcomeBroadcast(nextRoom, playerId)];
  const roster = rosterMessage(nextRoom);
  for (const pid of present) {
    if (pid !== playerId) broadcasts.push({ to: pid, message: roster });
  }
  return { room: nextRoom, broadcasts };
}

/**
 * Host starts the show from the lobby. Needs at least one seat. The question
 * is generated by the caller (server) and passed in, keeping this module free
 * of the pool and RNG.
 *
 * @param {Room} room
 * @param {string} playerId
 * @param {Question} question
 * @returns {ApplyResult}
 */
export function applyStart(room, playerId, question) {
  if (room.phase !== 'lobby') return { room, broadcasts: [] };
  if (room.hostId !== playerId) return { room, broadcasts: [] };
  if (room.seats.size === 0) return { room, broadcasts: [] };
  const nextRoom = { ...room, phase: /** @type {Phase} */ ('question'), roundIndex: 0, question, buzzes: [] };
  return { room: nextRoom, broadcasts: [questionBroadcast(nextRoom)] };
}

/**
 * A player buzzes with their chosen option. Correctness is resolved by the
 * caller (per the round's `isCorrect`) and passed in. Ignored unless we're in
 * the question phase, the player holds a seat, and they haven't already buzzed
 * this question — one buzz per player per question, first answer locked in.
 *
 * When every present seat has buzzed, the round auto-reveals (scores tally and
 * a `reveal` broadcast rides along).
 *
 * @param {Room} room
 * @param {string} playerId
 * @param {string} choice  the chosen option's code
 * @param {boolean} correct
 * @returns {ApplyResult}
 */
export function applyBuzz(room, playerId, choice, correct) {
  if (room.phase !== 'question') return { room, broadcasts: [] };
  if (!room.seats.has(playerId)) return { room, broadcasts: [] };
  if (room.buzzes.some((b) => b.playerId === playerId)) return { room, broadcasts: [] };

  const buzzes = [...room.buzzes, { playerId, choice, correct: !!correct }];
  const nextRoom = { ...room, buzzes };
  /** @type {Broadcast[]} */
  const broadcasts = [{
    to: 'all',
    message: {
      type: 'buzzed',
      playerId,
      buzzedCount: buzzes.length,
      seatCount: presentSeatCount(nextRoom),
    },
  }];

  if (allPresentBuzzed(nextRoom)) {
    const reveal = toReveal(nextRoom);
    return { room: reveal.room, broadcasts: [...broadcasts, ...reveal.broadcasts] };
  }
  return { room: nextRoom, broadcasts };
}

/**
 * Host ends the question early (its countdown ran out on the host page). Same
 * transition as the all-buzzed auto-reveal, just triggered by the timer
 * instead. Timing lives on the page; the room only knows "reveal now".
 *
 * @param {Room} room
 * @param {string} playerId
 * @returns {ApplyResult}
 */
export function applyForceReveal(room, playerId) {
  if (room.phase !== 'question') return { room, broadcasts: [] };
  if (room.hostId !== playerId) return { room, broadcasts: [] };
  return toReveal(room);
}

/**
 * Host advances from a reveal to the next question, or to the final board if
 * the last round just finished. The next question is generated by the caller;
 * it's ignored on the final round.
 *
 * @param {Room} room
 * @param {string} playerId
 * @param {Question} nextQuestion
 * @returns {ApplyResult}
 */
export function applyNext(room, playerId, nextQuestion) {
  if (room.phase !== 'reveal') return { room, broadcasts: [] };
  if (room.hostId !== playerId) return { room, broadcasts: [] };

  const isLast = room.roundIndex >= room.totalRounds - 1;
  if (isLast) {
    const nextRoom = { ...room, phase: /** @type {Phase} */ ('final'), question: null, buzzes: [] };
    return {
      room: nextRoom,
      broadcasts: [{ to: 'all', message: { type: 'final', scoreboard: scoreboardOf(nextRoom) } }],
    };
  }
  const nextRoom = {
    ...room,
    phase: /** @type {Phase} */ ('question'),
    roundIndex: room.roundIndex + 1,
    question: nextQuestion,
    buzzes: [],
  };
  return { room: nextRoom, broadcasts: [questionBroadcast(nextRoom)] };
}

/**
 * Host restarts from the final board: scores zeroed, back to the lobby so
 * people can leave or join before the next show.
 *
 * @param {Room} room
 * @param {string} playerId
 * @returns {ApplyResult}
 */
export function applyPlayAgain(room, playerId) {
  if (room.phase !== 'final') return { room, broadcasts: [] };
  if (room.hostId !== playerId) return { room, broadcasts: [] };
  const seats = new Map();
  for (const [pid, seat] of room.seats) seats.set(pid, { ...seat, score: 0 });
  const nextRoom = {
    ...room,
    phase: /** @type {Phase} */ ('lobby'),
    roundIndex: 0,
    question: null,
    buzzes: [],
    seats,
  };
  // A dedicated 'lobby' message (not just 'roster') so clients move their
  // phase back — 'roster' only refreshes the player list, it doesn't reset
  // the screen from the final board.
  return {
    room: nextRoom,
    broadcasts: [{ to: 'all', message: { type: 'lobby', hostId: nextRoom.hostId, roster: rosterList(nextRoom) } }],
  };
}

/**
 * A socket drops. The seat stays (sticky, for reconnect); the player just
 * leaves `present`. If a question was waiting only on the departed player,
 * it reveals now so the room doesn't hang.
 *
 * @param {Room} room
 * @param {string} playerId
 * @returns {ApplyResult}
 */
export function applyDisconnect(room, playerId) {
  if (!room.present.has(playerId)) return { room, broadcasts: [] };
  const present = new Set(room.present);
  present.delete(playerId);
  const nextRoom = { ...room, present };
  /** @type {Broadcast[]} */
  const broadcasts = [{ to: 'all', message: rosterMessage(nextRoom) }];
  if (nextRoom.phase === 'question' && allPresentBuzzed(nextRoom)) {
    const reveal = toReveal(nextRoom);
    return { room: reveal.room, broadcasts: [...broadcasts, ...reveal.broadcasts] };
  }
  return { room: nextRoom, broadcasts };
}

// ---- internal helpers ----

/**
 * Tally the current question and move to reveal. Speed bonus is off in solo
 * (one seat — no race). The reveal broadcast carries every player's pick so
 * clients can show "you vs them", not just a private right/wrong.
 *
 * @param {Room} room
 * @returns {ApplyResult}
 */
function toReveal(room) {
  const q = room.question;
  if (!q) return { room, broadcasts: [] };
  const points = scoreRound(room.buzzes, { applySpeedBonus: room.seats.size > 1 });
  const seats = new Map();
  for (const [pid, seat] of room.seats) {
    seats.set(pid, { ...seat, score: seat.score + (points[pid] ?? 0) });
  }
  const nextRoom = { ...room, phase: /** @type {Phase} */ ('reveal'), seats };
  /** @type {Record<string, string>} */
  const picks = {};
  for (const b of room.buzzes) picks[b.playerId] = b.choice;
  return {
    room: nextRoom,
    broadcasts: [{
      to: 'all',
      message: {
        type: 'reveal',
        answer: q.answer,
        picks,
        points,
        scoreboard: scoreboardOf(nextRoom),
        roundIndex: room.roundIndex,
        totalRounds: room.totalRounds,
        isFinalRound: room.roundIndex >= room.totalRounds - 1,
      },
    }],
  };
}

/**
 * True once every currently-present seat has buzzed (and at least one seat is
 * present). Disconnected seats don't hold up the reveal.
 *
 * @param {Room} room
 * @returns {boolean}
 */
function allPresentBuzzed(room) {
  const buzzed = new Set(room.buzzes.map((b) => b.playerId));
  let presentSeats = 0;
  for (const pid of room.seats.keys()) {
    if (!room.present.has(pid)) continue;
    presentSeats += 1;
    if (!buzzed.has(pid)) return false;
  }
  return presentSeats > 0;
}

/**
 * @param {Room} room
 * @returns {number}
 */
function presentSeatCount(room) {
  let n = 0;
  for (const pid of room.seats.keys()) if (room.present.has(pid)) n += 1;
  return n;
}

/**
 * @param {string} nickname
 * @returns {string}
 */
function cleanName(nickname) {
  return typeof nickname === 'string' ? nickname.trim().slice(0, 24) : '';
}

/**
 * @param {Room} room
 * @returns {Array<{ playerId: string, nickname: string, score: number, present: boolean }>}
 */
function rosterList(room) {
  const out = [];
  for (const [playerId, seat] of room.seats) {
    out.push({ playerId, nickname: seat.nickname, score: seat.score, present: room.present.has(playerId) });
  }
  return out;
}

/**
 * Roster sorted by score descending (seat order breaks ties, since Map
 * iteration is insertion-ordered and sort is stable).
 * @param {Room} room
 */
function scoreboardOf(room) {
  return rosterList(room).sort((a, b) => b.score - a.score);
}

/**
 * @param {Room} room
 * @returns {{ type: 'roster', hostId: string | null, roster: ReturnType<typeof rosterList> }}
 */
function rosterMessage(room) {
  return { type: 'roster', hostId: room.hostId, roster: rosterList(room) };
}

/**
 * The public view of a question — the answer is stripped so it never reaches
 * a client before reveal.
 * @param {Question} q
 */
function publicQuestion(q) {
  return { prompt: q.prompt, options: q.options };
}

/**
 * @param {Room} room
 * @returns {Broadcast}
 */
function questionBroadcast(room) {
  const q = room.question;
  const pub = q ? publicQuestion(q) : { prompt: '', options: [] };
  return {
    to: 'all',
    message: { type: 'question', ...pub, roundIndex: room.roundIndex, totalRounds: room.totalRounds },
  };
}

/**
 * Full resume snapshot for one player — enough to paint whatever phase the
 * room is in when they (re)connect.
 * @param {Room} room
 * @param {string} playerId
 * @returns {Broadcast}
 */
function welcomeBroadcast(room, playerId) {
  return {
    to: playerId,
    message: {
      type: 'welcome',
      you: playerId,
      isHost: room.hostId === playerId,
      phase: room.phase,
      roundIndex: room.roundIndex,
      totalRounds: room.totalRounds,
      roster: rosterList(room),
      question: room.question ? publicQuestion(room.question) : null,
      scoreboard: scoreboardOf(room),
    },
  };
}

// ---- persistence ----

/**
 * Structured-clone-safe snapshot for party storage. `present` is dropped (live
 * sockets don't survive a DO eviction) and everything else is plain data — no
 * predicates to strip, unlike TTT.
 * @param {Room} room
 */
export function serializeRoom(room) {
  return {
    phase: room.phase,
    hostId: room.hostId,
    seats: [...room.seats.entries()],
    totalRounds: room.totalRounds,
    roundIndex: room.roundIndex,
    question: room.question,
    buzzes: room.buzzes,
  };
}

/**
 * @param {any} snapshot
 * @returns {Room}
 */
export function deserializeRoom(snapshot) {
  return {
    phase: snapshot.phase ?? 'lobby',
    hostId: snapshot.hostId ?? null,
    seats: new Map(snapshot.seats ?? []),
    present: new Set(),
    totalRounds: snapshot.totalRounds ?? DEFAULT_ROUNDS,
    roundIndex: snapshot.roundIndex ?? 0,
    question: snapshot.question ?? null,
    buzzes: snapshot.buzzes ?? [],
  };
}
