/**
 * Generate continent silhouette SVGs for the flagQuiz picker tiles from
 * Natural Earth's 110m countries dataset.
 *
 * Natural Earth (naturalearthdata.com) is public domain — no attribution
 * required and no derivative restrictions, which makes it safe for any
 * future commercial use (paywall, ads, etc.) without licensing risk.
 *
 * Usage:
 *   1. Download the source GeoJSON:
 *      curl -sL -o ne_110m_countries.geojson \
 *        https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson
 *   2. Run from repo root with the GeoJSON path:
 *      node scripts/genContinentSvgs.mjs <path-to-geojson>
 *   3. SVGs land in flagQuiz/continents/.
 *
 * The world.svg (globe wireframe) is authored separately and NOT
 * regenerated by this script — a cartographic world map renders as
 * unrecognisable noise at 36 px icon size.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(__dirname, '..', 'flagQuiz', 'continents');
const VIEWBOX = 100;
const PADDING = 6;
// Douglas-Peucker tolerance in projected viewBox units (0..100). At ~0.4
// units, a vertex must move ≥0.4 to be kept — at the picker's 36 px display
// size that's ~0.14 px, invisible. Drops file size ~10× without affecting
// the rendered silhouette.
const SIMPLIFY_TOLERANCE = 0.4;
// Drop rings whose lat/lon bbox area is below this (sq degrees). Applied
// BEFORE computing the continent bbox, so it serves two purposes:
//
//   1. Tiny islands (Sicily, Malta, Cape Verde, scattered Pacific atolls)
//      vanish at 36 px display anyway and just bloat the path.
//   2. For Oceania specifically, the Pacific spread of small island states
//      otherwise inflates the bbox and shrinks Australia to a 3 px blob.
//      Filtering early lets Australia + NZ + PNG define the bbox.
//
// 3 sq deg keeps Iceland, Sicily, Cuba, Sri Lanka, NZ; drops Malta, Cyprus,
// most Caribbean micro-islands, and the bulk of Pacific island nations.
const MIN_RING_AREA_DEG = 3;

// CONTINENT property value in Natural Earth → output filename. Matches the
// VARIANTS keys in flags/quiz.js (minus 'countries', which uses world.svg).
const TARGETS = {
  Africa: 'africa.svg',
  Europe: 'europe.svg',
  Asia: 'asia.svg',
  'North America': 'north-america.svg',
  'South America': 'south-america.svg',
  Oceania: 'oceania.svg',
};

// Country NAMEs to exclude per continent — visual-only, the game's
// variant pool still includes every country Natural Earth classifies
// under the continent. Today this just trims Russia from Europe: NE
// classifies the whole of Russia (incl. Chukotka, +180°E) as Europe,
// which inflates the bbox to ~200° wide and shrinks recognisable
// Western Europe to a smear. Dropping Russia from the silhouette
// makes "Europe" actually read as Europe at 36 px.
const EXCLUDE_PER_CONTINENT = {
  Europe: new Set(['Russia']),
};

function main() {
  const src = process.argv[2];
  if (!src) {
    console.error('Usage: node scripts/genContinentSvgs.mjs <path-to-ne_110m_countries.geojson>');
    process.exit(1);
  }
  const geojson = JSON.parse(readFileSync(src, 'utf8'));

  for (const [continent, filename] of Object.entries(TARGETS)) {
    const excludes = EXCLUDE_PER_CONTINENT[continent];
    const features = geojson.features.filter((f) =>
      f.properties.CONTINENT === continent && !excludes?.has(f.properties.NAME),
    );
    if (features.length === 0) {
      console.warn(`No features for ${continent}, skipping`);
      continue;
    }
    const rings = collectRings(features);
    const fixed = rings.map(fixAntimeridian);
    const svg = renderSvg(fixed);
    const outPath = resolve(OUT_DIR, filename);
    writeFileSync(outPath, svg, 'utf8');
    console.log(`${filename}: ${rings.length} rings, ${svg.length} bytes`);
  }
}

/** @param {any[]} features */
function collectRings(features) {
  const rings = [];
  for (const f of features) {
    const geom = f.geometry;
    if (!geom) continue;
    if (geom.type === 'Polygon') {
      // First ring is outer; skip holes (negligible at 110 m, would
      // require even-odd fill anyway).
      rings.push(geom.coordinates[0]);
    } else if (geom.type === 'MultiPolygon') {
      for (const poly of geom.coordinates) rings.push(poly[0]);
    }
  }
  return rings;
}

/**
 * Polygon rings that cross the antimeridian (e.g. Chukotka, Fiji) come
 * back with vertices on both sides of ±180°, which projects to a horizontal
 * smear across the icon. Detect via wide longitude span and lift the
 * negative vertices into the +180..+360 range so the ring is contiguous.
 *
 * @param {number[][]} ring
 */
function fixAntimeridian(ring) {
  let minLon = Infinity;
  let maxLon = -Infinity;
  for (const [lon] of ring) {
    if (lon < minLon) minLon = lon;
    if (lon > maxLon) maxLon = lon;
  }
  if (maxLon - minLon <= 180) return ring;
  return ring.map(([lon, lat]) => [lon < 0 ? lon + 360 : lon, lat]);
}

/** @param {number[][][]} rings */
function renderSvg(rings) {
  // Filter tiny rings FIRST so the bbox is set by meaningful land masses.
  // Without this, Oceania's Pacific island spread blows the bbox wide
  // and shrinks Australia to a few pixels.
  const significant = rings.filter((ring) => ringBboxArea(ring) >= MIN_RING_AREA_DEG);
  // Equirectangular projection (lon → x, -lat → y), then bbox-fit into the
  // viewbox with uniform padding. Aspect ratio is preserved so a wide
  // continent (Asia) doesn't get squashed vertically.
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  for (const ring of significant) {
    for (const [lon, lat] of ring) {
      if (lon < minX) minX = lon;
      if (lon > maxX) maxX = lon;
      if (-lat < minY) minY = -lat;
      if (-lat > maxY) maxY = -lat;
    }
  }
  const w = maxX - minX;
  const h = maxY - minY;
  const target = VIEWBOX - 2 * PADDING;
  const scale = Math.min(target / w, target / h);
  const offsetX = (VIEWBOX - w * scale) / 2 - minX * scale;
  const offsetY = (VIEWBOX - h * scale) / 2 - minY * scale;
  const projected = significant.map((ring) =>
    ring.map(([lon, lat]) => [lon * scale + offsetX, -lat * scale + offsetY]),
  );
  const visible = projected.map((ring) => simplify(ring, SIMPLIFY_TOLERANCE));
  const fmt = (n) => n.toFixed(1);
  const d = visible.map((ring) => {
    const cmds = ring.map(([x, y], i) => `${i === 0 ? 'M' : 'L'}${fmt(x)},${fmt(y)}`);
    return cmds.join('') + 'Z';
  }).join('');
  // White fill (not grey) because some browsers default mask-image to
  // luminance-mode, where a 50% grey would mask at 50% opacity. White
  // gives full opacity in both alpha-mode and luminance-mode.
  return `<svg viewBox="0 0 ${VIEWBOX} ${VIEWBOX}" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path fill="#fff" fill-rule="evenodd" d="${d}"/></svg>\n`;
}

/** @param {number[][]} ring */
function ringBboxArea(ring) {
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity;
  for (const [x, y] of ring) {
    if (x < minX) minX = x;
    if (x > maxX) maxX = x;
    if (y < minY) minY = y;
    if (y > maxY) maxY = y;
  }
  return (maxX - minX) * (maxY - minY);
}

/**
 * Iterative Douglas-Peucker — keeps a vertex only when it lies further
 * than `tolerance` from the chord between its retained neighbours.
 * Iterative (stack-based) to avoid blowing the recursion limit on the
 * larger continents — Asia has rings with thousands of vertices.
 *
 * @param {number[][]} points
 * @param {number} tolerance
 */
function simplify(points, tolerance) {
  if (points.length < 4) return points;
  const keep = new Uint8Array(points.length);
  keep[0] = 1;
  keep[points.length - 1] = 1;
  /** @type {[number, number][]} */
  const stack = [[0, points.length - 1]];
  while (stack.length) {
    const [start, end] = /** @type {[number, number]} */ (stack.pop());
    let maxDist = 0;
    let maxIdx = -1;
    for (let i = start + 1; i < end; i++) {
      const d = perpDistance(points[i], points[start], points[end]);
      if (d > maxDist) { maxDist = d; maxIdx = i; }
    }
    if (maxDist > tolerance && maxIdx > -1) {
      keep[maxIdx] = 1;
      stack.push([start, maxIdx]);
      stack.push([maxIdx, end]);
    }
  }
  /** @type {number[][]} */
  const out = [];
  for (let i = 0; i < points.length; i++) {
    if (keep[i]) out.push(points[i]);
  }
  return out;
}

/**
 * @param {number[]} p
 * @param {number[]} a
 * @param {number[]} b
 */
function perpDistance(p, a, b) {
  const dx = b[0] - a[0];
  const dy = b[1] - a[1];
  if (dx === 0 && dy === 0) return Math.hypot(p[0] - a[0], p[1] - a[1]);
  const t = Math.max(0, Math.min(1, ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / (dx * dx + dy * dy)));
  return Math.hypot(p[0] - (a[0] + t * dx), p[1] - (a[1] + t * dy));
}

main();
