// Color palette used across all flags. Tests assert that no flag uses a colour
// outside this set, so typos like "yelow" or "lightblue" are caught at test time.
export const VALID_COLORS = [
  "red", "blue", "green", "yellow", "white", "black",
  "orange", "brown", "purple", "maroon",
];

export const flags = [
  // Europe
  { name: "Albania", colors: ["red", "black"], hasCoatOfArms: false, hasAnimal: true },
  { name: "Andorra", colors: ["blue", "yellow", "red"], hasCoatOfArms: true, hasAnimal: true },
  { name: "Armenia", colors: ["red", "blue", "orange"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Austria", colors: ["red", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Belarus", colors: ["red", "green", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Belgium", colors: ["black", "yellow", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Bosnia and Herzegovina", colors: ["blue", "yellow", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Bulgaria", colors: ["white", "green", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Croatia", colors: ["red", "white", "blue"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Cyprus", colors: ["white", "orange", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Czech Republic", colors: ["white", "red", "blue"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Denmark", colors: ["red", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Estonia", colors: ["blue", "black", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Finland", colors: ["white", "blue"], hasCoatOfArms: false, hasAnimal: false },
  { name: "France", colors: ["blue", "white", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Georgia", colors: ["white", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Germany", colors: ["black", "red", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Greece", colors: ["blue", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Hungary", colors: ["red", "white", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Iceland", colors: ["blue", "white", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Ireland", colors: ["green", "white", "orange"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Italy", colors: ["green", "white", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Kosovo", colors: ["blue", "yellow", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Latvia", colors: ["red", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Liechtenstein", colors: ["blue", "red", "yellow"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Lithuania", colors: ["yellow", "green", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Luxembourg", colors: ["red", "white", "blue"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Malta", colors: ["white", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Moldova", colors: ["blue", "yellow", "red"], hasCoatOfArms: true, hasAnimal: true },
  { name: "Monaco", colors: ["red", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Montenegro", colors: ["red", "yellow"], hasCoatOfArms: true, hasAnimal: true },
  { name: "Netherlands", colors: ["red", "white", "blue"], hasCoatOfArms: false, hasAnimal: false },
  { name: "North Macedonia", colors: ["red", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Norway", colors: ["red", "white", "blue"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Poland", colors: ["white", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Portugal", colors: ["green", "red", "yellow", "white", "blue"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Romania", colors: ["blue", "yellow", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Russia", colors: ["white", "blue", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "San Marino", colors: ["white", "blue"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Serbia", colors: ["red", "blue", "white"], hasCoatOfArms: true, hasAnimal: true },
  { name: "Slovakia", colors: ["white", "blue", "red"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Slovenia", colors: ["white", "blue", "red"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Spain", colors: ["red", "yellow"], hasCoatOfArms: true, hasAnimal: true },
  { name: "Sweden", colors: ["blue", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Switzerland", colors: ["red", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Turkey", colors: ["red", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Ukraine", colors: ["blue", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "United Kingdom", colors: ["blue", "white", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Vatican City", colors: ["yellow", "white"], hasCoatOfArms: true, hasAnimal: false },

  // Asia
  { name: "Afghanistan", colors: ["black", "red", "green", "white"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Azerbaijan", colors: ["blue", "red", "green", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Bahrain", colors: ["red", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Bangladesh", colors: ["green", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Bhutan", colors: ["yellow", "orange", "white"], hasCoatOfArms: false, hasAnimal: true },
  { name: "Brunei", colors: ["yellow", "white", "black", "red"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Cambodia", colors: ["blue", "red", "white"], hasCoatOfArms: true, hasAnimal: false },
  { name: "China", colors: ["red", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "India", colors: ["orange", "white", "green", "blue"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Indonesia", colors: ["red", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Iran", colors: ["green", "white", "red"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Iraq", colors: ["red", "white", "black", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Israel", colors: ["white", "blue"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Japan", colors: ["white", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Jordan", colors: ["black", "white", "green", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Kazakhstan", colors: ["blue", "yellow"], hasCoatOfArms: false, hasAnimal: true },
  { name: "Kuwait", colors: ["green", "white", "red", "black"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Kyrgyzstan", colors: ["red", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Laos", colors: ["red", "blue", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Lebanon", colors: ["red", "white", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Malaysia", colors: ["red", "white", "blue", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Maldives", colors: ["red", "green", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Mongolia", colors: ["red", "blue", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Myanmar", colors: ["yellow", "green", "red", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Nepal", colors: ["red", "blue", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "North Korea", colors: ["red", "white", "blue"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Oman", colors: ["red", "white", "green"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Pakistan", colors: ["green", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Palestine", colors: ["black", "white", "green", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Philippines", colors: ["blue", "red", "white", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Qatar", colors: ["maroon", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Saudi Arabia", colors: ["green", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Singapore", colors: ["red", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "South Korea", colors: ["white", "red", "blue", "black"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Sri Lanka", colors: ["yellow", "red", "green", "orange"], hasCoatOfArms: false, hasAnimal: true },
  { name: "Syria", colors: ["green", "white", "black", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Taiwan", colors: ["red", "blue", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Tajikistan", colors: ["red", "white", "green", "yellow"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Thailand", colors: ["red", "white", "blue"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Timor-Leste", colors: ["red", "yellow", "black", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Turkmenistan", colors: ["green", "red", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "United Arab Emirates", colors: ["red", "green", "white", "black"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Uzbekistan", colors: ["blue", "white", "red", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Vietnam", colors: ["red", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Yemen", colors: ["red", "white", "black"], hasCoatOfArms: false, hasAnimal: false },

  // Africa
  { name: "Algeria", colors: ["green", "white", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Angola", colors: ["red", "black", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Benin", colors: ["green", "yellow", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Botswana", colors: ["blue", "black", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Burkina Faso", colors: ["red", "green", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Burundi", colors: ["red", "white", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Cabo Verde", colors: ["blue", "white", "red", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Cameroon", colors: ["green", "red", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Central African Republic", colors: ["blue", "white", "green", "yellow", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Chad", colors: ["blue", "yellow", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Comoros", colors: ["yellow", "white", "red", "blue", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Republic of the Congo", colors: ["green", "yellow", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Democratic Republic of the Congo", colors: ["blue", "yellow", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Côte d'Ivoire", colors: ["orange", "white", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Djibouti", colors: ["blue", "green", "white", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Egypt", colors: ["red", "white", "black", "yellow"], hasCoatOfArms: true, hasAnimal: true },
  { name: "Equatorial Guinea", colors: ["green", "white", "red", "blue"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Eritrea", colors: ["red", "green", "blue", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Eswatini", colors: ["blue", "yellow", "red", "black", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Ethiopia", colors: ["green", "yellow", "red", "blue"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Gabon", colors: ["green", "yellow", "blue"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Gambia", colors: ["red", "blue", "green", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Ghana", colors: ["red", "yellow", "green", "black"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Guinea", colors: ["red", "yellow", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Guinea-Bissau", colors: ["red", "yellow", "green", "black"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Kenya", colors: ["black", "red", "green", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Lesotho", colors: ["blue", "white", "green", "black"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Liberia", colors: ["red", "white", "blue"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Libya", colors: ["red", "black", "green", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Madagascar", colors: ["white", "red", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Malawi", colors: ["black", "red", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Mali", colors: ["green", "yellow", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Mauritania", colors: ["green", "yellow", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Mauritius", colors: ["red", "blue", "yellow", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Morocco", colors: ["red", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Mozambique", colors: ["green", "white", "black", "yellow", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Namibia", colors: ["blue", "white", "red", "green", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Niger", colors: ["orange", "white", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Nigeria", colors: ["green", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Rwanda", colors: ["blue", "yellow", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "São Tomé and Príncipe", colors: ["green", "yellow", "red", "black"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Senegal", colors: ["green", "yellow", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Seychelles", colors: ["blue", "yellow", "red", "white", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Sierra Leone", colors: ["green", "white", "blue"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Somalia", colors: ["blue", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "South Africa", colors: ["green", "yellow", "black", "white", "red", "blue"], hasCoatOfArms: false, hasAnimal: false },
  { name: "South Sudan", colors: ["black", "red", "green", "white", "blue", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Sudan", colors: ["red", "white", "black", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Tanzania", colors: ["green", "yellow", "black", "blue"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Togo", colors: ["green", "yellow", "red", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Tunisia", colors: ["red", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Uganda", colors: ["black", "yellow", "red", "white"], hasCoatOfArms: false, hasAnimal: true },
  { name: "Zambia", colors: ["green", "red", "black", "orange"], hasCoatOfArms: false, hasAnimal: true },
  { name: "Zimbabwe", colors: ["green", "yellow", "red", "black", "white"], hasCoatOfArms: false, hasAnimal: true },

  // Americas
  { name: "Antigua and Barbuda", colors: ["red", "white", "black", "blue", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Argentina", colors: ["blue", "white", "yellow"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Bahamas", colors: ["blue", "yellow", "black"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Barbados", colors: ["blue", "yellow", "black"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Belize", colors: ["blue", "red", "white", "yellow", "green", "brown"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Bolivia", colors: ["red", "yellow", "green"], hasCoatOfArms: true, hasAnimal: true },
  { name: "Brazil", colors: ["green", "yellow", "blue", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Canada", colors: ["red", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Chile", colors: ["red", "white", "blue"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Colombia", colors: ["yellow", "blue", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Costa Rica", colors: ["blue", "white", "red"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Cuba", colors: ["blue", "white", "red"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Dominica", colors: ["green", "yellow", "black", "white", "red", "purple"], hasCoatOfArms: false, hasAnimal: true },
  { name: "Dominican Republic", colors: ["blue", "red", "white"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Ecuador", colors: ["yellow", "blue", "red"], hasCoatOfArms: true, hasAnimal: true },
  { name: "El Salvador", colors: ["blue", "white"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Grenada", colors: ["red", "yellow", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Guatemala", colors: ["blue", "white"], hasCoatOfArms: true, hasAnimal: true },
  { name: "Guyana", colors: ["green", "red", "white", "yellow", "black"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Haiti", colors: ["blue", "red"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Honduras", colors: ["blue", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Jamaica", colors: ["green", "yellow", "black"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Mexico", colors: ["green", "white", "red"], hasCoatOfArms: true, hasAnimal: true },
  { name: "Nicaragua", colors: ["blue", "white"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Panama", colors: ["red", "blue", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Paraguay", colors: ["red", "white", "blue"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Peru", colors: ["red", "white"], hasCoatOfArms: true, hasAnimal: true },
  { name: "Saint Kitts and Nevis", colors: ["green", "yellow", "black", "red", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Saint Lucia", colors: ["blue", "yellow", "black", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Saint Vincent and the Grenadines", colors: ["blue", "yellow", "green"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Suriname", colors: ["green", "white", "red", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Trinidad and Tobago", colors: ["red", "black", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "United States", colors: ["red", "white", "blue"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Uruguay", colors: ["blue", "white", "yellow"], hasCoatOfArms: true, hasAnimal: false },
  { name: "Venezuela", colors: ["yellow", "blue", "red", "white"], hasCoatOfArms: true, hasAnimal: true },

  // Oceania
  { name: "Australia", colors: ["blue", "red", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Fiji", colors: ["blue", "red", "white", "yellow"], hasCoatOfArms: true, hasAnimal: true },
  { name: "Kiribati", colors: ["red", "white", "blue", "yellow"], hasCoatOfArms: false, hasAnimal: true },
  { name: "Marshall Islands", colors: ["blue", "orange", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Micronesia", colors: ["blue", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Nauru", colors: ["blue", "yellow", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "New Zealand", colors: ["blue", "red", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Palau", colors: ["blue", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Papua New Guinea", colors: ["red", "black", "yellow", "white"], hasCoatOfArms: false, hasAnimal: true },
  { name: "Samoa", colors: ["red", "blue", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Solomon Islands", colors: ["blue", "green", "yellow", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Tonga", colors: ["red", "white"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Tuvalu", colors: ["blue", "red", "white", "yellow"], hasCoatOfArms: false, hasAnimal: false },
  { name: "Vanuatu", colors: ["red", "green", "black", "yellow"], hasCoatOfArms: true, hasAnimal: false },
];

export const criteria = {
  hasRed:        { label: "Has red",          test: f => f.colors.includes("red") },
  hasGreen:      { label: "Has green",        test: f => f.colors.includes("green") },
  has4Colors:    { label: "Has 4+ colors",    test: f => f.colors.length >= 4 },
  hasAnimal:     { label: "Has an animal",    test: f => f.hasAnimal },
  hasCoatOfArms: { label: "Has coat of arms", test: f => f.hasCoatOfArms },
  noWhite:       { label: "No white",         test: f => !f.colors.includes("white") },
};

export const rowKeys = ["hasRed", "hasGreen", "has4Colors"];
export const colKeys = ["hasAnimal", "hasCoatOfArms", "noWhite"];

export function normalise(str) {
  return str.trim().toLowerCase().replace(/[^a-z0-9 ]/g, "");
}

export function buildGrid() {
  return rowKeys.flatMap(rk =>
    colKeys.map(ck => ({
      rowKey: rk,
      colKey: ck,
      validFlags: flags.filter(f => criteria[rk].test(f) && criteria[ck].test(f)),
    }))
  );
}
